/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
import { createOpenApiHttp } from "openapi-msw"
import { type HttpHandler } from "msw"
import type { paths } from "@/schema"

const baseUrl = ""
export const http = createOpenApiHttp<paths>({ baseUrl })

export const handlers: HttpHandler[] = [
  http.get(`${baseUrl}/me`, ({ response }) => {
    return response(200).json(examples.Me.value)
  }),
  http.get(`${baseUrl}/reviews`, ({ response }) => {
    return response(200).json([...examples.ReviewListResponse.value])
  }),
  http.post(`${baseUrl}/reviews`, ({ response }) => {
    return response(201).empty()
  }),
  http.put(`${baseUrl}/reviews/{id}`, ({ response }) => {
    return response(200).json(examples.ReviewResponse.value)
  }),
  http.delete(`${baseUrl}/reviews/{id}`, ({ response }) => {
    return response(204).empty()
  }),
]

const examples = {
  ReviewListResponse: { value: [{ id: "1", title: "title", content: "content" }] },
  ReviewResponse: { value: { id: "1", title: "title", content: "content" } },
  Me: { value: { name: "name", userRole: "ADMIN" } },
} as const
